[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_sort_within_sections = true
line_length = 100
known_firstparty = ["config", "dataset", "train", "transform", "utils", "hub", "checkpoint"]

sections = [
    "FUTURE",
    "STDLIB",
    "THIRDPARTY",
    "INTERNAL",
    "FIRSTPARTY",
    "LOCALFOLDER",
]

import_heading_stdlib = "Standard Library"
import_heading_firstparty = "simple_classifier"
import_heading_third_party = "ThirdParty"
import_heading_local_folder = "LocalPkg"


[tool.black]
line_length = 100


[tool.ruff]
ignore = ["E741"]
line-length = 100


[tool.pytest.ini_options]
addopts = "--cov=simple_classifier --capture=no"


[tool.mypy]
ignore_missing_imports = true
